import Navbar from "@/components/navbar/Navbar";
import "../styles/globals.css";
import { Nunito } from "next/font/google";

const nunitoFont = Nunito({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={nunitoFont.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
